# Generated by Django 3.1 on 2022-07-13 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20220712_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 16, 11, 24, 191333), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 16, 11, 24, 191352), verbose_name='修改时间'),
        ),
    ]
