# Generated by Django 3.1 on 2022-07-16 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20220716_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 16, 22, 55, 30, 835671), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 16, 22, 55, 30, 835688), verbose_name='修改时间'),
        ),
    ]
